## 랜덤 포레스트

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()
train_input, test_input, train_target, test_target = train_test_split(data, target,test_size=0.2,random_state = 42)

In [2]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)

In [4]:
scores = cross_validate(rf, train_input, train_target,
                       return_train_score=True , n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


In [5]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


In [6]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8934000384837406


## 엑스트라 트리

In [11]:
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
et.fit(train_input, train_target)
train_score = et.score(train_input, train_target)
test_score = et.score(test_input, test_target)

print(np.mean(train_score), np.mean(test_score))

0.996921300750433 0.8861538461538462


In [12]:
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


## 그레이디언트 부스팅

In [18]:
from sklearn.ensemble import GradientBoostingClassifier
gd = GradientBoostingClassifier(random_state = 42)
scores = cross_validate(gd, train_input, train_target, 
                       return_train_score = True, n_jobs=-1)
print(np.mean(train_score), np.mean(test_score))

0.996921300750433 0.8861538461538462


In [20]:
gd = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2,
                               random_state=42)
score = cross_validate(gd, train_input, train_target,
                      return_train_score=True, n_jobs=-1)
print(np.mean(train_score), np.mean(test_score))

0.996921300750433 0.8861538461538462


In [21]:
gd.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


## 히스토리 기반 그레디언트 부스팅

In [24]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgd = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgd, train_input, train_target,
                       return_train_score=True)
print(np.mean(train_score), np.mean(test_score))

0.996921300750433 0.8861538461538462


In [30]:
from sklearn.inspection import permutation_importance

hgd.fit(train_input, train_target)
result = permutation_importance(hgd, train_input, train_target,
                                n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.08876275 0.23438522 0.08027708]


In [31]:
result = permutation_importance(hgd, test_input, test_target,
                                n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.05969231 0.20238462 0.049     ]


In [32]:
hgd.score(test_input, test_target)

0.8723076923076923

In [39]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [41]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method = 'hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target,
                       return_train_score = True)
print(np.mean(train_score), np.mean(test_score))

0.996921300750433 0.8861538461538462


In [47]:
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9558403027491312 0.8782000074035686
